version: '3.8'
services:
  db:
    image: postgres:14.4
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=asdfasdf
      - PGDATA=/data/postgres
    volumes:
      - ./postgres:/data/postgres
    ports:
      - '5432:5432'
  redis:
    image: redis:7.0.5
    restart: always
    ports:
      - '6379:6379'
