# Generated by Django 4.1 on 2022-08-26 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloud_id', models.CharField(blank=None, max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name='server',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('starting', 'starting'), ('running', 'running'), ('stopping', 'stopping'), ('stopped', 'stopped'), ('terminating', 'terminating'), ('terminated', 'terminated')], max_length=16),
        ),
        migrations.CreateModel(
            name='ServerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orchestrator.server')),
            ],
        ),
        migrations.AddField(
            model_name='server',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orchestrator.image'),
        ),
    ]
