# Generated by Django 4.1 on 2022-08-26 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0002_image_alter_server_status_serverrequest_server_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverrequest',
            name='body',
            field=models.JSONField(default=dict),
        ),
    ]
