# Generated by Django 4.1 on 2022-08-26 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0005_server_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CloudServiceProperties',
            new_name='CloudServiceProperty',
        ),
    ]
