# Generated by Django 4.1 on 2022-08-26 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0007_alter_cloudserviceproperty_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstanceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='server',
            name='instance_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orchestrator.instancetype'),
            preserve_default=False,
        ),
    ]
