# Generated by Django 4.1 on 2022-08-26 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0009_alter_server_instance_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='cloud_service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='orchestrator.cloudserivce'),
            preserve_default=False,
        ),
    ]
