# Generated by Django 4.1 on 2022-09-13 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0010_server_cloud_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverrequest',
            name='name',
            field=models.CharField(default='', max_length=256),
        ),
    ]
