# Generated by Django 4.1 on 2022-09-29 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0012_rename_cloudserivce_cloudservice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serverrequest',
            name='name',
        ),
        migrations.AddField(
            model_name='serverrequest',
            name='message',
            field=models.CharField(default='', max_length=256),
        ),
    ]
