# Generated by Django 4.1 on 2022-10-05 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0014_serverrequest_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serverrequest',
            name='server',
        ),
        migrations.AddField(
            model_name='serverrequest',
            name='object_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
