"""
Django settings for orc project.

Generated by 'django-admin startproject' using Django 4.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""
import sys
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-hl0(-+8#z371(&96+ol95r!m(&yyykw&tpsr#3n_6_k!fbs%si'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'orchestrator.apps.OrchestratorConfig'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'orc.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'orc.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'orc',
        'USER': 'admin',
        'PASSWORD': 'asdfasdf',
        'HOST': 'localhost',
        'PORT': '5432'
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

USER = 'shiggy'
AWS_QUEUE_PREFIX=f'{USER}-'

# duplicate definition, inspect later
AWS_MESSAGE_QUEUE_NAME = f'{AWS_QUEUE_PREFIX}message-queue'
AWS_QUEUE_URL = f'https://sqs.us-east-1.amazonaws.com/733435515506/{AWS_MESSAGE_QUEUE_NAME}'

AWS_KEY='AKIA2VRBJ2JZHT2RPGIJ'
AWS_SECRET='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'
REGION='us-east-1'

_handlers = [] if len(sys.argv) > 0 and sys.argv[1] == 'shell' else ['console']


LOGGER = {
        'version': 1,
        'disable_existing_loggers': True,
        "formatters": {
            "verbose": {
                "format": "%(levelname)s %(asctime)s %(filename)s:%(lineno)s %(thread)d  | %(message)s"
            },
        },
        "handlers": {
            "console": {
                "class": "logging.StreamHandler",
                "level": "DEBUG", # if frame.gateway.configuration.RUNTIME.DEBUG else "INFO",
                "formatter": "verbose",
                "stream": "ext://sys.stdout"
            },
            'null': {
                'class': 'logging.NullHandler',
                'level': 'DEBUG'
            },
        },
        'loggers': {
            "__main__": {
                "handlers": _handlers,
                "level": "DEBUG",
                "propagate": True,
            },
            "sentry_sdk.errors": {
                'handlers': _handlers,
                "level": "DEBUG",
                "propagate": True,
            },
            "orchestrator": {
                'handlers': _handlers,
                "level": "DEBUG",
                "propagate": True,
            },
        }
    }
